<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Image Generator</title>
</head>
<body>

    <h1>Welcome to Our Shop!</h1>
    <p>Here is an image generated by PHP:</p>
    <div>
        <img src="data:image/png;base64,<?php
            // Start output buffering
            ob_start();

            // Create the image
            $image = imagecreate(400, 100);

            // Colors
            $blue = imagecolorallocate($image, 0, 0, 255);
            $white = imagecolorallocate($image, 255, 255, 255);

            // Add text
            imagestring($image, 5, 50, 40, "Welcome to Our Shop!", $white);

            // Output the image as a base64-encoded string
            imagepng($image);
            $image_data = ob_get_clean();

            // Free memory
            imagedestroy($image);

            // Echo the base64-encoded string
            echo base64_encode($image_data);
        ?>" alt="Welcome Banner">
    </div>

</body>
</html>
